### ISSUE TITLE
切换主题时发生NPE

### ISSUE THREAD

**Issue by liongoodvery** [li-yu/FakeWeather#6]
```
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.animation.Animator$AnimatorListener.onAnimationStart(android.animation.Animator)' on a null object reference
                                                                        at android.animation.AnimatorSet.start(AnimatorSet.java:651)
                                                                        at com.liyu.fakeweather.ui.weather.dynamic.SunnyType.endAnimation(SunnyType.java:354)
                                                                        at com.liyu.fakeweather.ui.weather.dynamic.DynamicWeatherView.onDestroy(DynamicWeatherView.java:130)
                                                                        at com.liyu.fakeweather.ui.weather.WeatherFragment.onDestroy(WeatherFragment.java:205)
                                                                        at android.support.v4.app.Fragment.performDestroy(Fragment.java:2434)
                                                                     
```

不能添加NULL给animSet
```
if (listener != null) {
      animSet.addListener(listener);
 }
```

**Comment by li-yu** [comment]
收到，感谢！下个版本修复。

**Comment by li-yu** [comment]
@liongoodvery 已更新到 v1.3.1
